---
- name: Deploy a VM from a Content Library template (vSphere REST)
  hosts: localhost
  gather_facts: false

  vars:
    # --- vCenter auth ---
    vcenter_hostname: "vcenter.example.com"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "{{ vault_vcenter_password }}"
    vcenter_validate_certs_opt: false  

    # --- what to deploy ---
    new_vm_name: "rhel9-from-template-01"
    template_name: "RHEL9.6Base-Subscribed"     # content library item name (template)

    # --- placement (adjust to your inventory) ---
    cluster_path: "/MNS/MNS"
    rp_path: "/MNS/MNS/Resources"
    folder_path: "/MNS/MNS/Greg/redhat"
    datastore_path: "/MNS/MNS/SSD"

    # optional post-deploy tweaks
    cpu_count: 2
    mem_mib: 4096
    power_on_after_deploy: true

  tasks:
    - name: Resolve placement MOIDs
      set_fact:
        cluster_id: "{{ lookup('vmware.vmware.cluster_moid', cluster_path) }}"
        rp_id: "{{ lookup('vmware.vmware.resource_pool_moid', rp_path) }}"
        folder_id: "{{ lookup('vmware.vmware.folder_moid', folder_path) }}"
        ds_id: "{{ lookup('vmware.vmware.datastore_moid', datastore_path) }}"


    - name: Check if VM already exists (idempotency)
      vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs_opt }}"
        name: "{{ new_vm_name }}"
      register: vm_lookup

    - name: Get local content libraries
      when: vm_lookup.virtual_machines | length == 0
      vmware.vmware.content_library_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs_opt }}"
      register: libs

    - name: Choose a library (adjust selection logic if you have several)
      when: vm_lookup.virtual_machines | length == 0
      set_fact:
        lib_id: "{{ libs.libraries[0].id }}"

    - name: List items in the chosen library
      when: vm_lookup.virtual_machines | length == 0
      vmware.vmware.content_library_item_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs_opt }}"
        library_id: "{{ lib_id }}"
      register: lib_items

  # Removed duplicate task for listing items in the chosen library (REST)

    - name: Find the template item by name
      when: vm_lookup.virtual_machines | length == 0
      set_fact:
        template_item: >-
          {{ (lib_items.library_items | selectattr('name', 'equalto', template_name) | list)[0] }}

    - name: Deploy VM from content library template
      when: vm_lookup.virtual_machines | length == 0
      vmware.vmware.deploy_template:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs_opt }}"
        template_src: "{{ template_item.id }}"
        name: "{{ new_vm_name }}"
        cluster: "{{ cluster_id }}"
        resource_pool: "{{ rp_id }}"
        folder: "{{ folder_id }}"
        datastore: "{{ ds_id }}"
      register: deployed

    - name: Determine VM id (newly created or pre-existing)
      set_fact:
        vm_id: >-
          {{ (deployed.instance | default(omit)) |
             default( (vm_lookup.virtual_machines[0].moid) if (vm_lookup.virtual_machines | length > 0) else omit ) }}

    - name: (Optional) Adjust CPU and memory
      when: vm_id is defined
      vmware.vmware.vm:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs_opt }}"
        moid: "{{ vm_id }}"
        hardware:
          num_cpus: "{{ cpu_count }}"
          memory_mb: "{{ mem_mib }}"
        state: present

    - name: Power on the VM
      when: vm_id is defined and power_on_after_deploy
      vmware.vmware.vm_power:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs_opt }}"
        moid: "{{ vm_id }}"
        state: powered_on
